-- PostgreSQL Optimized Schema Setup
SET client_min_messages = WARNING;

-- -------------------------------------------------------------
-- CREATE TABLES
-- -------------------------------------------------------------

-- Table: groups
CREATE TABLE IF NOT EXISTS groups (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: file_uploads
CREATE TABLE IF NOT EXISTS file_uploads (
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NULL,
    status VARCHAR(50) NOT NULL CONSTRAINT chk_file_uploads_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: files
CREATE TABLE IF NOT EXISTS files (
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    mime_type VARCHAR(100) NULL,
    is_latest BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: file_sharing
CREATE TABLE IF NOT EXISTS file_sharing (
    id UUID NOT NULL PRIMARY KEY,
    file_id UUID NOT NULL,
    user_id UUID NULL,
    type VARCHAR(50) NOT NULL CONSTRAINT chk_file_sharing_type CHECK (type IN ('PUBLIC', 'PRIVATE')),
    expiry TIMESTAMPTZ(6) NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_sharing_on_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE
);

-- Table: participants
CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id UUID NOT NULL,
    member_id UUID NOT NULL,
    member_type VARCHAR(50) NOT NULL CONSTRAINT chk_participants_member_type CHECK (member_type IN ('OWNER', 'EDITOR', 'VIEWER')),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participants_on_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);

-- Table: file_accesses
CREATE TABLE IF NOT EXISTS file_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id UUID NOT NULL,
    group_id UUID NULL,
    user_id UUID NULL,
    type VARCHAR(50) NOT NULL CONSTRAINT chk_file_accesses_type CHECK (type IN ('OWNER', 'MEMBER', 'GROUP')),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_accesses_on_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_accesses_on_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL
);


-- -------------------------------------------------------------
-- PERFORMANCE & INDEXATION OPTIMIZATIONS
-- -------------------------------------------------------------

-- Foreign Key B-Tree Indexes (Prevents sequential scans on joins/deletes)
CREATE INDEX IF NOT EXISTS idx_file_sharing_file_id ON file_sharing (file_id);
CREATE INDEX IF NOT EXISTS idx_participants_group_id ON participants (group_id);
CREATE INDEX IF NOT EXISTS idx_file_accesses_file_id ON file_accesses (file_id);
CREATE INDEX IF NOT EXISTS idx_file_accesses_group_id ON file_accesses (group_id);

-- Lookup Performance Indexes
CREATE INDEX IF NOT EXISTS idx_participants_member_lookup ON participants (member_id);
CREATE INDEX IF NOT EXISTS idx_file_accesses_user_lookup ON file_accesses (user_id) WHERE user_id IS NOT NULL;

-- Soft-Delete & Versioning Partial Index (Massive space and scan optimization)
CREATE INDEX IF NOT EXISTS idx_files_active_latest ON files (id) 
WHERE is_deleted = FALSE AND is_latest = TRUE;

-- Speeds up scheduled deletes by targeting stale rows instantly
CREATE INDEX IF NOT EXISTS idx_file_uploads_cleanup ON file_uploads (status, created_at) 
WHERE status = 'IN_PROGRESS';