-- PostgreSQL Optimized Schema
SET client_min_messages = WARNING;

-- -------------------------------------------------------------
-- CREATE TABLES
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS groups (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(400) NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS file_uploads (
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NULL,
    status VARCHAR(255) NOT NULL
        CONSTRAINT chk_file_uploads_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS folders (
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NULL,
    group_id UUID NULL,
    parent_id UUID NULL,
    name VARCHAR(255) NOT NULL,

    is_root BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_folders_group
        FOREIGN KEY (group_id)
        REFERENCES groups (id),

    CONSTRAINT fk_folders_parent
        FOREIGN KEY (parent_id)
        REFERENCES folders (id)
);


CREATE TABLE IF NOT EXISTS files (
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NULL,
    folder_id UUID NULL,

    file_name VARCHAR(100) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NULL,

    is_latest BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_files_folder
        FOREIGN KEY (folder_id)
        REFERENCES folders (id)
);


CREATE TABLE IF NOT EXISTS file_sharing (
    id UUID NOT NULL PRIMARY KEY,
    file_id UUID NOT NULL,
    user_id UUID NULL,

    type VARCHAR(255) NOT NULL
        CONSTRAINT chk_file_sharing_type
        CHECK (type IN ('PUBLIC', 'PRIVATE')),

    expiry TIMESTAMP(6) NULL,

    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_file_sharing_file
        FOREIGN KEY (file_id)
        REFERENCES files (id)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id UUID NOT NULL,
    member_id UUID NOT NULL,

    member_type VARCHAR(255) NOT NULL
        CONSTRAINT chk_participants_member_type
        CHECK (member_type IN ('OWNER', 'EDITOR', 'VIEWER')),

    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_participants_group
        FOREIGN KEY (group_id)
        REFERENCES groups (id)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS file_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id UUID NOT NULL,
    group_id UUID NULL,
    user_id UUID NULL,

    type VARCHAR(255) NOT NULL
        CONSTRAINT chk_file_accesses_type
        CHECK (type IN ('OWNER', 'MEMBER', 'GROUP')),

    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_file_accesses_file
        FOREIGN KEY (file_id)
        REFERENCES files (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_file_accesses_group
        FOREIGN KEY (group_id)
        REFERENCES groups (id)
        ON DELETE SET NULL
);


-- -------------------------------------------------------------
-- PERFORMANCE & INDEXATION
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- Folder indexes
-- -------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS uq_folders_one_root_per_owner
    ON folders (owner_id)
    WHERE is_root = TRUE;

-- Fast lookup of active children of a folder.
CREATE INDEX IF NOT EXISTS idx_folders_active_by_parent
    ON folders (parent_id)
    WHERE is_deleted = FALSE;


-- Useful when listing a user's active folders.
CREATE INDEX IF NOT EXISTS idx_folders_active_by_owner
    ON folders (owner_id)
    WHERE is_deleted = FALSE;


-- Useful for group-based folder queries.
CREATE INDEX IF NOT EXISTS idx_folders_group_id
    ON folders (group_id);


-- -------------------------------------------------------------
-- File indexes
-- -------------------------------------------------------------

-- Fast lookup of files belonging to a folder.
CREATE INDEX IF NOT EXISTS idx_files_folder_id
    ON files (folder_id);


-- Fast lookup of active/latest files in a folder.
CREATE INDEX IF NOT EXISTS idx_files_active_latest_by_folder
    ON files (folder_id)
    WHERE is_deleted = FALSE
      AND is_latest = TRUE;


-- Fast lookup of a user's active/latest files.
CREATE INDEX IF NOT EXISTS idx_files_active_latest_by_owner
    ON files (owner_id)
    WHERE is_deleted = FALSE
      AND is_latest = TRUE;


-- -------------------------------------------------------------
-- File sharing indexes
-- -------------------------------------------------------------

-- Foreign-key lookup.
CREATE INDEX IF NOT EXISTS idx_file_sharing_file_id
    ON file_sharing (file_id);


-- Useful for user-specific sharing lookups.
CREATE INDEX IF NOT EXISTS idx_file_sharing_user_id
    ON file_sharing (user_id)
    WHERE user_id IS NOT NULL;


-- -------------------------------------------------------------
-- Participant indexes
-- -------------------------------------------------------------

-- Foreign-key lookup.
CREATE INDEX IF NOT EXISTS idx_participants_group_id
    ON participants (group_id);


-- Fast lookup of groups for a particular member.
CREATE INDEX IF NOT EXISTS idx_participants_member_lookup
    ON participants (member_id);


-- Useful for checking a member's role within a group.
CREATE INDEX IF NOT EXISTS idx_participants_group_member
    ON participants (group_id, member_id);


-- -------------------------------------------------------------
-- File access indexes
-- -------------------------------------------------------------

-- Foreign-key lookup.
CREATE INDEX IF NOT EXISTS idx_file_accesses_file_id
    ON file_accesses (file_id);


-- Foreign-key lookup.
CREATE INDEX IF NOT EXISTS idx_file_accesses_group_id
    ON file_accesses (group_id);


-- Fast lookup of files accessible by a user.
CREATE INDEX IF NOT EXISTS idx_file_accesses_user_lookup
    ON file_accesses (user_id)
    WHERE user_id IS NOT NULL;


-- Useful for group-based access checks.
CREATE INDEX IF NOT EXISTS idx_file_accesses_group_file
    ON file_accesses (group_id, file_id)
    WHERE group_id IS NOT NULL;


-- -------------------------------------------------------------
-- File lifecycle
-- -------------------------------------------------------------

-- Fast lookup of active/latest files.
CREATE INDEX IF NOT EXISTS idx_files_active_latest
    ON files (id)
    WHERE is_deleted = FALSE
      AND is_latest = TRUE;


-- -------------------------------------------------------------
-- Upload cleanup
-- -------------------------------------------------------------

-- Speeds up identification of stale in-progress uploads.
CREATE INDEX IF NOT EXISTS idx_file_uploads_cleanup
    ON file_uploads (status, created_at)
    WHERE status = 'IN_PROGRESS';